/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.util.List;

/**
 *
 * @author Sorathan
 */
public class Knapsack_Window extends javax.swing.JFrame {

    /**
     * Creates new form Knapsack_Window
     */
    public GUIPage gData;
    public ANSWERGui aData; 
    public Knapsack_Window(GUIPage g,ANSWERGui a) {
        this.gData = g;
        this.aData = a;
        initComponents();
    }

    private Knapsack_Window() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Helping = new javax.swing.JButton();
        DataSorting = new javax.swing.JButton();
        DATAAnswer = new javax.swing.JButton();
        CLOSEGUI = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Angsana New", 0, 48)); // NOI18N
        jLabel1.setText("Branch And Bound For 0-1Knapsack Problem");

        Helping.setFont(new java.awt.Font("Angsana New", 0, 36)); // NOI18N
        Helping.setText("Helping");
        Helping.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HelpingActionPerformed(evt);
            }
        });

        DataSorting.setFont(new java.awt.Font("Angsana New", 0, 36)); // NOI18N
        DataSorting.setText("Show SortData");
        DataSorting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataSortingActionPerformed(evt);
            }
        });

        DATAAnswer.setFont(new java.awt.Font("Angsana New", 0, 36)); // NOI18N
        DATAAnswer.setText("ANSWER");
        DATAAnswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DATAAnswerActionPerformed(evt);
            }
        });

        CLOSEGUI.setFont(new java.awt.Font("Angsana New", 0, 36)); // NOI18N
        CLOSEGUI.setText("EXIT PROGRAM");
        CLOSEGUI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLOSEGUIActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(296, 296, 296)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(DataSorting)
                            .addComponent(Helping, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DATAAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addComponent(CLOSEGUI)))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(Helping, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(DataSorting, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(DATAAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CLOSEGUI, javax.swing.GroupLayout.PREFERRED_SIZE, 47, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DataSortingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataSortingActionPerformed
        GUIPage g = gData;
        g.setVisible(true);
        //g.setText(Input(this.dataItem));
    }//GEN-LAST:event_DataSortingActionPerformed

    private void DATAAnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DATAAnswerActionPerformed
        // TODO add your handling code here:
        ANSWERGui answer = aData;
        answer.setVisible(true);
    }//GEN-LAST:event_DATAAnswerActionPerformed

    private void CLOSEGUIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLOSEGUIActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_CLOSEGUIActionPerformed

    private void HelpingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HelpingActionPerformed
        // TODO add your handling code here:
        HelpingGUI helpWindow = new HelpingGUI();
        helpWindow.setVisible(true);
    }//GEN-LAST:event_HelpingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Knapsack_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Knapsack_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Knapsack_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Knapsack_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Knapsack_Window().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CLOSEGUI;
    private javax.swing.JButton DATAAnswer;
    private javax.swing.JButton DataSorting;
    private javax.swing.JButton Helping;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
